#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'
cookbook 'apache2'
cookbook 'python'
cookbook 'redisio'

# Example syntax for other forms of Cheffile
# entries.
#
# cookbook 'chef-client'
# cookbook 'apache2', '>= 1.0.0'
# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'
# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
